# yy??key
message:
  push:
    Yy:
      YyKey: epng87dlcn05sgnq
      weatherFor7DayApi: http://api.yytianqi.com/forecast7d?
      realTimeApi: http://api.yytianqi.com/observe?
    common:
      loveDay: 2018-03-02
      birthDay: 1996-05-17
    Tx:
      TxKey: 93d614525302804825d024ce743d95a1
      TxUrl: https://apis.tianapi.com/caihongpi/index?
    Wx:
      appId: wxa2661fb2ab2ed060
      secretKey: 640643cf7555860310feb49b87379de1
      userId: oJOr658VgVRUGr24j8q3GtFYubZk
      templateId: wsk-EbBAefSTn8dyVwJNC04y83dg0RLLIDIHQCSTU_Q
